"""Algorithm implementations for the teaching demonstrations."""

from .consecutive_days_off import (
    DAYS,
    RESTAURANT_REQUIREMENTS,
    DaysOffStep,
    EmployeeAssignment,
    PairOption,
    build_employee_schedule,
    calculate_daily_staffing,
    calculate_excess_staffing,
    generate_consecutive_days_off_steps,
)

from .johnson import (
    ORIGINAL_SEQUENCE,
    PRINT_SHOP_JOBS,
    Candidate,
    DecisionStep,
    Job,
    Metrics,
    Operation,
    Schedule,
    build_two_resource_schedule,
    calculate_metrics,
    generate_johnson_steps,
)
from .single_processor import (
    FABRICATION_JOBS,
    SequencedOperation,
    SequencingJob,
    SequencingMetrics,
    SingleProcessorSchedule,
    build_single_processor_schedule,
    calculate_sequencing_metrics,
    sequence_edd,
    sequence_fcfs,
    sequence_spt,
)

__all__ = [
    "DAYS",
    "RESTAURANT_REQUIREMENTS",
    "DaysOffStep",
    "EmployeeAssignment",
    "PairOption",
    "ORIGINAL_SEQUENCE",
    "PRINT_SHOP_JOBS",
    "Candidate",
    "DecisionStep",
    "Job",
    "Metrics",
    "Operation",
    "Schedule",
    "build_two_resource_schedule",
    "build_employee_schedule",
    "calculate_daily_staffing",
    "calculate_excess_staffing",
    "calculate_metrics",
    "generate_consecutive_days_off_steps",
    "generate_johnson_steps",
    "FABRICATION_JOBS",
    "SequencedOperation",
    "SequencingJob",
    "SequencingMetrics",
    "SingleProcessorSchedule",
    "build_single_processor_schedule",
    "calculate_sequencing_metrics",
    "sequence_edd",
    "sequence_fcfs",
    "sequence_spt",
]
